### ISSUE TITLE
Why the mirror don't reflect the sea?

### ISSUE THREAD

**Issue by KnewHow** [ssloy/tinyraytracer#23]
the picture link is: https://github.com/KnewHow/TinyRayTracer/blob/add_background/out.jpg

**Comment by ssloy** [comment]
Because you need to pick the color from the envmap here:
https://github.com/KnewHow/TinyRayTracer/blob/6ef1a4f33ee572bd1e86e095e6bb6af91478ca64/renderer.cpp#L36

You use the initial ray to pick the color, and the final one is to be used.

**Comment by KnewHow** [comment]
Thank you very match, I have got it!
