### ISSUE TITLE
Can't get right render image.

### ISSUE THREAD

**Issue by eclair-lumiere** [ssloy/tinyraytracer#26]
Used the corresponding code in wiki page, but got wrong picture.
Step 1:

![image](https://user-images.githubusercontent.com/38656355/131913027-62ec6684-0444-47de-ab49-b15707d50a52.png)

Step 4:
![image](https://user-images.githubusercontent.com/38656355/131912439-470d84d8-ac4a-4b72-804b-dac4cea9c155.png)

(Also step 2 got a strange picture.)
IDE: visual studio community 2019 16.10.2(/std:c++latest)
CPU: r5 5600x

I have no idea about it. Thank you very much!

**Comment by ssloy** [comment]
Check [this issue](https://github.com/ssloy/tinyraycaster/issues/9)

**Comment by eclair-lumiere** [comment]
Thank you for your response! 
Solved the problem by setting ofstream mode.
