### ISSUE TITLE
Integer FOV value

### ISSUE THREAD

**Issue by cl0ne** [ssloy/tinyraytracer#8]
https://github.com/ssloy/tinyraytracer/blob/edfb292caad134a9c2df154edc050fb6c6ec3a31/tinyraytracer.cpp#L124
Shouldn't we use `float` here instead of `int`?

**Comment by ssloy** [comment]
nice catch, fixed, thank you.

**Comment by ema2159** [comment]
Just in case anyone is asking themselves (like myself) why their results are not matching with the result images shown in the walkthrough, using int instead of float causes an implicit cast which causes the fov value to be exactly 1. So, in most steps, the camera's FOV is set to 1.
